fly: behaviour: fix fly login on zero-column terminals
Our unit test suite was failing on our darwin and windows workers due to
the following error message: https://ci.concourse-ci.org/teams/main/pipelines/concourse/jobs/unit/builds/323#L5eea6b9f:103

```
error: liner: function not supported in this terminal
```

This occurs in the liner package when running the `PasswordPrompt` when
one of the following occurs:

1. the terminal isn't supported (which we were already covering)
2. the number of columns is 0

Rather than trying to infer from the error message (which is generally
considered bad practice and could be brittle), fallback to the
non-password prompt on any error (that isn't a Ctrl+C or EOF).

Note that I haven't actually tested this since I'm not sure how to
simulate a zero-width terminal

Signed-off-by: Aidan Oldershaw <aoldershaw@pivotal.io>