worker: add build constraints to `containerd.go`
Without the constraint, `concourse` will simply not compile as such file
contains constructs only present in `linux`-based compilations.

Also, given that at the moment we're focusing solely on the linux
implementation, there's no need to bother about the other cases (darwin &
windows).

e.g., on Windows:

	unknown field 'Pdeathsig' in struct literal of type syscall.SysProcAttr
	Error: exit status 2

ref: https://golang.org/pkg/go/build/#hdr-Build_Constraints

Signed-off-by: Ciro S. Costa <cscosta@pivotal.io>